export { DisplayHero } from './DisplayHero';
export { DisplayGrand } from './DisplayGrand';
export { DisplayLead } from './DisplayLead';
export { DisplayTitle } from './DisplayTitle';
export { DisplayHead } from './DisplayHead';
export { BodyLg } from './BodyLg';
export { BodyMd } from './BodyMd';
export { BodySm } from './BodySm';
export { MicroCaps } from './MicroCaps';
